<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	<title>Loading Editor</title>
	<link rel="stylesheet" type="text/css" href="<? echo(CMS::Singleton()->document_root) ?>/skin/style.css" />
</head>
<body>
	<div class="centered">
	<table>
		<tr>
			<td align="center"><p>Now loading...</p></td>
			<td align="center"><img src="<? echo(CMS::Singleton()->document_root) ?>/skin/z-loading.gif" alt=""/></td>
			<td align="center"><p>...please wait</p></td>
		</tr>
	</table>
	</div>
</body>
</html>
